### ISSUE TITLE
BadStatusLine: ''

### ISSUE THREAD

**Issue by peterhurford** [charityscience/csh-sms#67]
```
 Traceback (most recent call last):
   File "/home/ubuntu/.virtualenvs/csh/local/lib/python2.7/site-packages/django_crontab/crontab.py", line 145, in run_job
     func(*job_args, **job_kwargs)
   File "/home/ubuntu/csh-sms/jobs/text_processor_job.py", line 7, in check_and_process_registrations
     messages = Texter().read_inbox()
   File "/home/ubuntu/csh-sms/modules/texter.py", line 8, in read_inbox
     num_message_dict = textlocal.new_messages_by_number()
   File "/home/ubuntu/csh-sms/modules/textlocalwrapper.py", line 59, in new_messages_by_number
     all_messages = self.get_primary_inbox_messages()
   File "/home/ubuntu/csh-sms/modules/textlocalwrapper.py", line 37, in get_primary_inbox_messages
     return self.get_primary_inbox()['messages']
   File "/home/ubuntu/csh-sms/modules/textlocalwrapper.py", line 28, in get_primary_inbox
     return self.get_url_response(request_url=messages_url, params=params)
   File "/home/ubuntu/csh-sms/modules/textlocalwrapper.py", line 32, in get_url_response
     f = request.urlopen(request_url + parse.urlencode(params))
   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib/python2.7/urllib2.py", line 429, in open
     response = self._open(req, data)
   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
     '_open', req)
   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
     result = func(*args)
   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
     context=self._context)
   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
     r = h.getresponse(buffering=True)
   File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
     response.begin()
   File "/usr/lib/python2.7/httplib.py", line 453, in begin
     version, status, reason = self._read_status()
   File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
     raise BadStatusLine(line)
 BadStatusLine: ''
```

**Comment by peterhurford** [comment]
Occurs in the logs on:

2017-10-16 12:00:12,014
2017-10-16 14:10:12,019
2017-10-16 14:20:11,467
2017-10-16 16:00:12,239
2017-10-17 13:30:11,397

**Comment by peterhurford** [comment]
StackOverflow says this issue is an external API problem, see https://stackoverflow.com/questions/8734617/python-django-badstatusline-error

> The BadStatusLine exception is raised when you call urllib2.urlopen(url) and the remote server responds with a status code that python cannot understand.

> Assuming that you don't control url, you can't prevent this from happening. All you can do is catch the exception, and manage it gracefully.

So this means that TextLocal is producing an error when we call the API. I assume this could happen from now and then. The fact that we retry just a few minutes later likely means it is not a serious issue (unless it starts happening a ton in a row). It is not a problem with our code.

We could handle the error with a clear message if we desire?
